<a href="https://colab.research.google.com/github/SanjaySaatyaki/pytorch_4_ml_dl/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as bp
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Tensor as Int
scalar.item()

7

In [5]:
vector = torch.tensor([7,8])

In [6]:
vector

tensor([7, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,9],[8,3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[1,5,8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 5, 8]])

In [16]:
#Random Tensor
random_tensor = torch.rand(3,5)

In [17]:
random_tensor

tensor([[0.8079, 0.0796, 0.6138, 0.6791, 0.7576],
        [0.0828, 0.8237, 0.8039, 0.7223, 0.9670],
        [0.7406, 0.0374, 0.7077, 0.7843, 0.3416]])

In [18]:
random_tensor.ndim

2

In [19]:
random_img_size_tensor = torch.rand(255,255,3)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([255, 255, 3]), 3)

##Zeros and ones

In [20]:
zeros = torch.zeros(3,4)

In [21]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

#Creating range of tensor and tensor like

In [24]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#torch with step
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

Creating tensor like

In [26]:
one_to_ten = torch.arange(1,11,1)

In [27]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros = torch.zeros_like(one_to_ten)

In [29]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [30]:
float_32_tensor = torch.tensor([2.0,4.,5.],dtype=None)

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = torch.tensor([2.0,4.,5.],dtype=torch.float16)

In [33]:
float_16_tensor.dtype

torch.float16

In [34]:
#important params dtype, device, required grad
#dtype 32 bit float and 16 bit float
#Most of error
#Tensor not correct dtype
#tensor not shape
#tensor not on right device

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 4., 5.], dtype=torch.float16)

In [36]:
float_16_tensor*float_32_tensor

tensor([ 4., 16., 25.])

In [37]:
int_32_tensor = torch.tensor([3,4,5])

In [38]:
int_32_tensor.dtype

torch.int64

In [39]:
float_32_tensor * int_32_tensor

tensor([ 6., 16., 25.])

Getting information from Tensor
datatype - tensor.dtype
shape - tensor.shape
device = tensor.device

In [40]:
rand_tensor = torch.rand(3,4)

In [41]:
rand_tensor.dtype

torch.float32

In [42]:
rand_tensor.shape

torch.Size([3, 4])

In [43]:
rand_tensor.device

device(type='cpu')

## Manipulating Tensors(tensor operations)
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [44]:
tensor = torch.randint(0,10,size=(3,))
tensor

tensor([8, 9, 6])

In [45]:
tensor +10

tensor([18, 19, 16])

In [46]:
tensor * 10

tensor([80, 90, 60])

In [47]:
tensor - 10

tensor([-2, -1, -4])

In [48]:
torch.mul(tensor,10)

tensor([80, 90, 60])

# Matrix Multiplication

* Elementwise
* Matric Multiplication

# Rules:

* Inner Dimensions should match
* resulting matrix of shpae of outer dimensions


In [49]:
tensor * tensor

tensor([64, 81, 36])

In [50]:
torch.matmul(tensor,tensor)

tensor(181)

In [51]:
tensor_A = torch.rand(3,2)

In [52]:
tensor_B = torch.rand(3,2)

In [53]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues, we can manipulate the shape of one of our tensor

In [54]:
tensor_B.T , tensor_B.T.shape

(tensor([[0.5593, 0.5367, 0.8480],
         [0.8943, 0.6304, 0.4090]]),
 torch.Size([2, 3]))

In [55]:
tensor_B, tensor_B.shape

(tensor([[0.5593, 0.8943],
         [0.5367, 0.6304],
         [0.8480, 0.4090]]),
 torch.Size([3, 2]))

In [56]:
torch.mm(tensor_A, tensor_B.T)

tensor([[1.1340, 0.9300, 1.0618],
        [0.7223, 0.6041, 0.7252],
        [0.5490, 0.4658, 0.5790]])

# Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [58]:
#Create a tensor
x = torch.arange(0,100,10)

In [59]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
x.dtype

torch.int64

In [60]:
torch.min(x)

tensor(0)

In [61]:
torch.max(x)

tensor(90)

In [65]:
#Troch.mean() requires a tensor of float32
torch.mean(x.type(torch.float32))

tensor(45.)

In [67]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min, max

In [68]:
x.argmin()

tensor(0)

In [69]:
x.argmax()

tensor(9)

In [71]:
x[x.argmin()]

tensor(0)

In [72]:
x[x.argmax()]

tensor(90)

## Reshaping, Stacking, Squeezing, Unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Returns a view of an input tensor of certain shape but keep the same memory
- Stacking - Combine multiple tensors either horizontally or vertically
- Squeeze  - removes all '1' dimensions from a tensor
- Unsqueeze  - add a '1' dimension to a tensor
- Permute - Return a view of the input with dimension permuted(swapped) in a certain way

In [73]:
x = torch.arange(1.,10.)

In [76]:
x_reshaped = x.reshape(1,9)

In [77]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
x_reshaped = x.reshape(9,1)

In [79]:
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [81]:
#Change the view
z = x.view(1,9)

In [82]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
#Changing z changes x (view shares the same memory)

In [87]:
z[ :, 0 ] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [88]:
x_stacked = torch.stack([x,x,x,x])

In [90]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])