<a href="https://colab.research.google.com/github/SanjaySaatyaki/pytorch_4_ml_dl/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as bp
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Tensor as Int
scalar.item()

7

In [5]:
vector = torch.tensor([7,8])

In [6]:
vector

tensor([7, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,9],[8,3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[1,5,8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 5, 8]])

In [16]:
#Random Tensor
random_tensor = torch.rand(3,5)

In [17]:
random_tensor

tensor([[0.2875, 0.9223, 0.2516, 0.0700, 0.5381],
        [0.8848, 0.6537, 0.9938, 0.6779, 0.6394],
        [0.5741, 0.7746, 0.8328, 0.1381, 0.6651]])

In [18]:
random_tensor.ndim

2

In [19]:
random_img_size_tensor = torch.rand(255,255,3)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([255, 255, 3]), 3)

##Zeros and ones

In [20]:
zeros = torch.zeros(3,4)

In [21]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

#Creating range of tensor and tensor like

In [24]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#torch with step
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

Creating tensor like

In [26]:
one_to_ten = torch.arange(1,11,1)

In [27]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros = torch.zeros_like(one_to_ten)

In [29]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [30]:
float_32_tensor = torch.tensor([2.0,4.,5.],dtype=None)

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = torch.tensor([2.0,4.,5.],dtype=torch.float16)

In [33]:
float_16_tensor.dtype

torch.float16

In [34]:
#important params dtype, device, required grad
#dtype 32 bit float and 16 bit float
#Most of error
#Tensor not correct dtype
#tensor not shape
#tensor not on right device

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 4., 5.], dtype=torch.float16)

In [36]:
float_16_tensor*float_32_tensor

tensor([ 4., 16., 25.])

In [37]:
int_32_tensor = torch.tensor([3,4,5])

In [38]:
int_32_tensor.dtype

torch.int64

In [39]:
float_32_tensor * int_32_tensor

tensor([ 6., 16., 25.])

Getting information from Tensor
datatype - tensor.dtype
shape - tensor.shape
device = tensor.device

In [40]:
rand_tensor = torch.rand(3,4)

In [41]:
rand_tensor.dtype

torch.float32

In [42]:
rand_tensor.shape

torch.Size([3, 4])

In [43]:
rand_tensor.device

device(type='cpu')

## Manipulating Tensors(tensor operations)
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [44]:
tensor = torch.randint(0,10,size=(3,))
tensor

tensor([8, 0, 9])

In [45]:
tensor +10

tensor([18, 10, 19])

In [46]:
tensor * 10

tensor([80,  0, 90])

In [47]:
tensor - 10

tensor([ -2, -10,  -1])

In [48]:
torch.mul(tensor,10)

tensor([80,  0, 90])

# Matrix Multiplication

* Elementwise
* Matric Multiplication

# Rules:

* Inner Dimensions should match
* resulting matrix of shpae of outer dimensions


In [49]:
tensor * tensor

tensor([64,  0, 81])

In [50]:
torch.matmul(tensor,tensor)

tensor(145)

In [51]:
tensor_A = torch.rand(3,2)

In [52]:
tensor_B = torch.rand(3,2)

In [57]:
#Failure
# torch.mm(tensor_A, tensor_B)

To fix tensor shape issues, we can manipulate the shape of one of our tensor

In [54]:
tensor_B.T , tensor_B.T.shape

(tensor([[0.8239, 0.3726, 0.0443],
         [0.2316, 0.2825, 0.0269]]),
 torch.Size([2, 3]))

In [55]:
tensor_B, tensor_B.shape

(tensor([[0.8239, 0.2316],
         [0.3726, 0.2825],
         [0.0443, 0.0269]]),
 torch.Size([3, 2]))

In [58]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.2973, 0.1631, 0.0183],
        [0.7654, 0.4637, 0.0507],
        [0.3707, 0.1979, 0.0224]])

# Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [59]:
#Create a tensor
x = torch.arange(0,100,10)

In [60]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
x.dtype

torch.int64

In [62]:
torch.min(x)

tensor(0)

In [63]:
torch.max(x)

tensor(90)

In [64]:
#Troch.mean() requires a tensor of float32
torch.mean(x.type(torch.float32))

tensor(45.)

In [65]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min, max

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[x.argmin()]

tensor(0)

In [69]:
x[x.argmax()]

tensor(90)

## Reshaping, Stacking, Squeezing, Unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Returns a view of an input tensor of certain shape but keep the same memory
- Stacking - Combine multiple tensors either horizontally or vertically
- Squeeze  - removes all '1' dimensions from a tensor
- Unsqueeze  - add a '1' dimension to a tensor
- Permute - Return a view of the input with dimension permuted(swapped) in a certain way

In [70]:
x = torch.arange(1.,10.)

In [71]:
x_reshaped = x.reshape(1,9)

In [72]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
x_reshaped = x.reshape(9,1)

In [74]:
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [75]:
#Change the view
z = x.view(1,9)

In [76]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
#Changing z changes x (view shares the same memory)

In [78]:
z[ :, 0 ] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
x_stacked = torch.stack([x,x,x,x])

In [80]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [81]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [82]:
x_reshaped.shape

torch.Size([9, 1])

In [88]:
x_reshaped = x_reshaped.reshape(1,9)

In [89]:
x_reshaped.shape

torch.Size([1, 9])

In [90]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
x_squeezed = x_reshaped.squeeze()

In [94]:
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [96]:
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed_1,x_unsqueezed_1.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [98]:
#torch.premute
#re arrange

In [101]:
rand_tensor = torch.rand(224,224,3)

In [102]:
rand_tensor

tensor([[[0.2524, 0.5317, 0.4505],
         [0.8149, 0.8205, 0.5941],
         [0.7489, 0.4161, 0.7598],
         ...,
         [0.1775, 0.9944, 0.2421],
         [0.5759, 0.8780, 0.6594],
         [0.9107, 0.8299, 0.0123]],

        [[0.0427, 0.0698, 0.4364],
         [0.3476, 0.5571, 0.9898],
         [0.5055, 0.4634, 0.5655],
         ...,
         [0.8858, 0.5128, 0.1608],
         [0.2600, 0.1420, 0.2155],
         [0.9662, 0.7669, 0.0809]],

        [[0.4478, 0.3512, 0.5080],
         [0.7639, 0.6852, 0.0904],
         [0.2159, 0.0645, 0.1896],
         ...,
         [0.2433, 0.7192, 0.5800],
         [0.4198, 0.6082, 0.3904],
         [0.1029, 0.6889, 0.4720]],

        ...,

        [[0.0051, 0.4219, 0.8172],
         [0.0854, 0.5115, 0.9540],
         [0.5795, 0.4585, 0.6594],
         ...,
         [0.8853, 0.4063, 0.1284],
         [0.6187, 0.2813, 0.0298],
         [0.4334, 0.6540, 0.9513]],

        [[0.6399, 0.8287, 0.9311],
         [0.9695, 0.9357, 0.0907],
         [0.

In [103]:
x_permuted = rand_tensor.permute(2,0,1)#shift axis 0-1,1-2,2-0

In [104]:
x_permuted.shape

torch.Size([3, 224, 224])

#indexing - Selecting data from tensor

In [105]:
import torch

In [106]:
x = torch.arange(1,10)

In [107]:
x = x.reshape(1,3,3)

In [108]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [110]:
#index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [113]:
x[0,0,0]

tensor(1)

In [114]:
x[0,1,1]

tensor(5)

In [116]:
x[0,2,2]

tensor(9)

In [117]:
#: to select all of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [118]:
# get all values of 0th dimension and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [119]:
#Get all values of 0th dim and 1st index of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [120]:
#get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [121]:
#index on x to return 9
x[0,2,2]

tensor(9)

In [124]:
#index of x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

# Pytorch Tensors and Numpy
Numpy is popular scientific python numerical computing library

and python has func to interact with it

* Data in Numpy, want in pytorch Tensor 'torch.from_numpy(ndarray)
* Pytorch tensor ->Numpy->'torch.Tensor.numpy()

In [125]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#by default the numpy will convert to float64

In [126]:
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [127]:
#Change the value of array
array = array + 1

In [128]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
#Tensor to numpy
tensor = torch.ones(7)

In [130]:
numpy_tensor = tensor.numpy()

In [131]:
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [132]:
#change the tensor what happens to numpy
tensor = tensor +1

In [133]:
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (Trying to take random out of random)

- to reduce randomness in nn and pytroch comes concept of **random seed**
what the random seed does is "flavor" the randomness

In [134]:
torch.rand(3,3)

tensor([[0.0616, 0.3763, 0.1218],
        [0.4591, 0.9280, 0.9238],
        [0.0749, 0.6743, 0.4500]])

In [135]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A,random_tensor_B

(tensor([[0.4339, 0.6586, 0.1298, 0.9519],
         [0.7970, 0.3173, 0.4323, 0.8436],
         [0.6179, 0.4566, 0.9110, 0.8604]]),
 tensor([[0.6337, 0.9577, 0.3058, 0.8108],
         [0.3333, 0.8501, 0.1162, 0.0508],
         [0.4503, 0.1476, 0.0656, 0.5849]]))

In [137]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [139]:
# Random but reproducible tensor
import torch

RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [140]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
### GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [2]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
torch.cuda.device_count()

1

In [4]:
tensor = torch.tensor([1,2,3],device="cpu")

In [5]:
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [12]:
tensor_on_gpu = tensor.to(device)

In [13]:
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [8]:
### Move tensor back to cpu

In [10]:
tensor_on_gpu = tensor_on_gpu.to(device="cpu")
tensor_on_gpu

tensor([1, 2, 3])

In [11]:
print(tensor_on_gpu.device)

cpu


In [14]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])