<a href="https://colab.research.google.com/github/SanjaySaatyaki/pytorch_4_ml_dl/blob/main/pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import torch
import pandas as pd
import numpy as bp
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [62]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [63]:
scalar.ndim

0

In [64]:
#Tensor as Int
scalar.item()

7

In [65]:
vector = torch.tensor([7,8])

In [66]:
vector

tensor([7, 8])

In [67]:
vector.ndim

1

In [68]:
vector.shape

torch.Size([2])

In [69]:
MATRIX = torch.tensor([[7,9],[8,3]])

In [70]:
MATRIX.ndim

2

In [71]:
MATRIX.shape

torch.Size([2, 2])

In [72]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[1,5,8]]])

In [73]:
TENSOR.ndim

3

In [74]:
TENSOR.shape

torch.Size([1, 3, 3])

In [75]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 5, 8]])

In [76]:
#Random Tensor
random_tensor = torch.rand(3,5)

In [77]:
random_tensor

tensor([[0.5212, 0.9385, 0.7654, 0.9925, 0.7565],
        [0.6782, 0.6509, 0.1008, 0.9740, 0.3379],
        [0.3872, 0.5775, 0.3677, 0.1648, 0.7040]])

In [78]:
random_tensor.ndim

2

In [79]:
random_img_size_tensor = torch.rand(255,255,3)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([255, 255, 3]), 3)

##Zeros and ones

In [80]:
zeros = torch.zeros(3,4)

In [81]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [82]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
ones.dtype

torch.float32

#Creating range of tensor and tensor like

In [84]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#torch with step
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

Creating tensor like

In [86]:
one_to_ten = torch.arange(1,11,1)

In [87]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
ten_zeros = torch.zeros_like(one_to_ten)

In [89]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [90]:
float_32_tensor = torch.tensor([2.0,4.,5.],dtype=None)

In [91]:
float_32_tensor.dtype

torch.float32

In [92]:
float_16_tensor = torch.tensor([2.0,4.,5.],dtype=torch.float16)

In [93]:
float_16_tensor.dtype

torch.float16

In [94]:
#important params dtype, device, required grad
#dtype 32 bit float and 16 bit float
#Most of error
#Tensor not correct dtype
#tensor not shape
#tensor not on right device

In [95]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 4., 5.], dtype=torch.float16)

In [96]:
float_16_tensor*float_32_tensor

tensor([ 4., 16., 25.])

In [97]:
int_32_tensor = torch.tensor([3,4,5])

In [98]:
int_32_tensor.dtype

torch.int64

In [99]:
float_32_tensor * int_32_tensor

tensor([ 6., 16., 25.])

Getting information from Tensor
datatype - tensor.dtype
shape - tensor.shape
device = tensor.device

In [100]:
rand_tensor = torch.rand(3,4)

In [101]:
rand_tensor.dtype

torch.float32

In [102]:
rand_tensor.shape

torch.Size([3, 4])

In [103]:
rand_tensor.device

device(type='cpu')

## Manipulating Tensors(tensor operations)
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [104]:
tensor = torch.randint(0,10,size=(3,))
tensor

tensor([8, 5, 4])

In [105]:
tensor +10

tensor([18, 15, 14])

In [106]:
tensor * 10

tensor([80, 50, 40])

In [107]:
tensor - 10

tensor([-2, -5, -6])

In [108]:
torch.mul(tensor,10)

tensor([80, 50, 40])

# Matrix Multiplication

* Elementwise
* Matric Multiplication

# Rules:

* Inner Dimensions should match
* resulting matrix of shpae of outer dimensions


In [109]:
tensor * tensor

tensor([64, 25, 16])

In [110]:
torch.matmul(tensor,tensor)

tensor(105)

In [113]:
tensor_A = torch.rand(3,2)

In [114]:
tensor_B = torch.rand(3,2)

In [115]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues, we can manipulate the shape of one of our tensor

In [118]:
tensor_B.T , tensor_B.T.shape

(tensor([[0.0931, 0.6672, 0.5066],
         [0.6035, 0.6882, 0.4838]]),
 torch.Size([2, 3]))

In [119]:
tensor_B, tensor_B.shape

(tensor([[0.0931, 0.6035],
         [0.6672, 0.6882],
         [0.5066, 0.4838]]),
 torch.Size([3, 2]))

In [120]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.4764, 0.8313, 0.6036],
        [0.4069, 0.8848, 0.6501],
        [0.6220, 0.8430, 0.6015]])